# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    install:
      - pip install -U pip
      - pip install .
      - pip install --group docs
    post_checkout:
      # Avoid setuptools-scm dirty Git index issues
      - git reset --hard HEAD
      - git clean -fdx

formats:
  - pdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  fail_on_warning: true
  configuration: doc/source/conf.py
